
tasks:
  - name: Terminal 1
    init: echo 'init script' # runs during prebuild
    command: echo 'start script'
  - name: Terminal 2
    init: echo 'This is terminal 2'

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - mblode.pretty-formatter